add

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -25,11 +25,20 @@ jobs:
       #   timeout-minutes: 5
       #   env:
       #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      - uses: SonarSource/sonarqube-quality-gate-action@v1
+      - name: Check Quality Gate
+        id: qualitygate
+        uses: SonarSource/sonarqube-quality-gate-action@v1
+        continue-on-error: true
         timeout-minutes: 5
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
       - name: Custom Failure Message
-        if: failure()
-        run: echo "::error::❌ SonarQube Quality Gate Failed! Fix issues before proceeding."
+        run: |
+          if [ "${{ steps.qualitygate.outcome }}" != "success" ]; then
+            echo "::error::❌ SonarQube Quality Gate Failed!"
+            echo "🚫 Fix bugs, vulnerabilities, and code smells before merging."
+            exit 1
+          else
+            echo "✅ Quality Gate Passed!"
+          fi
